### ISSUE TITLE
Can you explain janusgraph-env with air-routes.graphml example????

### ISSUE THREAD

**Issue by NK-NK** [armandleopold/janusgraph-deployement#1]
Can you explain janusgraph-env with **air-routes.graphml** example????
@erandal 

graph ml file link:
**https://raw.githubusercontent.com/krlawrence/graph/master/sample-data/air-routes.graphml**

**Comment by erandal** [comment]
Ok, this will take some time, but i will work on it, i promise ;)

**Comment by armandleopold** [comment]
Hello NK, i haven(t got the time to do your request, you can run the stack by reading the README file & learning how to use Janusgraph & Tinkerpop on the different related documentation.
Have fun with your graph ! =)
